# Generated by Django 6.1.1 on 2026-09-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaccion',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='transacciones', to='gestion.etiqueta'),
        ),
    ]
