# Generated by Django 6.1.1 on 2026-09-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_cuenta_saldo_alter_transaccion_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('deposito', 'Depósito'), ('retiro', 'Retiro')], max_length=20),
        ),
    ]
