# Generated by Django 6.1.1 on 2026-09-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_transaccion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('RETIRO', 'Retiro')], max_length=20),
        ),
    ]
